[project]
name = "irobot-khr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mediapipe>=0.10.20",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
]
